### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by jimlynnjulian** [XMB5/mkclean-pragmatic#1]
I've found media servers like Emby, Jellyfin, and Plex disallow ff & rev in files converted to mkv using mkvmerge in the gui. The problem seems to be split seekhead elements; one part at the head of the file and another part at the end. Applying mkvmerge from a script corrects the problem. But given very many files, detecting and fixing problem files could be very tedious and time consuming. Using output from mkvalidate fed into a python script then forwarded to mkclean could automate the process. This is still a lengthy task.
Working the seekhead elements directly would be much quicker.
Would your app speed things up?
Thank you, Jim Julian

**Comment by jimlynnjulian** [comment]
Just tried compiling. The compile instructions do not work.
Ignore 'mkdir build'; 'cd build'.
Do 'cmake CMakeLists.txt'
This seems to work, but mkclean is not recognized as a valid command, afterwards.

**Comment by lehuymanhtan** [comment]
hi, i got the same problem as you. so how do you fix this issue?
> Applying mkvmerge from a script corrects the problem.

can you tell me what command do you use?

**Comment by jimlynnjulian** [comment]
The error I address is the split seekhead problem. No ffwd or rev.
Some variant of Linux Subsystem for Windows has to be installed in order to run the commands. 
This may work on a Linux machine, I haven't tested.
This a batch mode.

For single files:
Just do [mkvmerge --output.mkv input.mp4] or  [mkvmerge --output.mkv input.mkv] for a single file. This will fix most. Mkclean will work if mkvmerge does not. Mkclean is better but time consuming.

Batch mode:
Place mkvtools on system path or in same folder as file.
Download and install rip-grep and do the same. 
Rename rip-grep.exe to rg.exe for convenience.

The first command finds all movies in a folder and subfolders and runs mkvinfo.
Mkvinfo output is sent to a text file ' file_mkvi.txt'.
# In Linux bash window:

find . -name "*.mkv" -exec bash -c 'for f; do mkvinfo -v -v "${f%.*}.mkv" | sed -e '\''/+ Cluster/q'\'' > "${f%.mkv}-mkvi.txt" ; IFS=#; readlink -f ${f##*/} >> _f.txt; done' -- {} +

rg.exe -l "KaxSeekHead" -g '*.txt'

# Problem files will be listed and highlighted in blue on the screen.
# Copy results from the screen to notepad++ or other text editor.
# Replace [-mkvi.txt\r\n] with [.mkv"\r\nmkclean "]
# Fix first and last lines of edited list.
# Copy&Paste in the bash window.
# Watch for 0 byte outputs in files if breaks or processor overload occur during processing.
Hope this helps. good luck.

**Comment by jimlynnjulian** [comment]
The error I address is the split seekhead problem. No ffwd or rev.
Some variant of Linux Subsystem for Windows has to be installed in order to run the commands. 
This may work on a Linux machine, I haven't tested.
This a batch mode.

For single files:
Just do [mkvmerge --output.mkv input.mp4] or  [mkvmerge --output.mkv input.mkv] for a single file. This will fix most. Mkclean will work if mkvmerge does not. Mkclean is better but time consuming.

Batch mode:
Place mkvtools on system path or in same folder as file.
Download and install rip-grep and do the same. 
Rename rip-grep.exe to rg.exe for convenience.

The first command finds all movies in a folder and subfolders and runs mkvinfo.
Mkvinfo output is sent to a text file ' file_mkvi.txt'.
# In Linux bash window:

find . -name "*.mkv" -exec bash -c 'for f; do mkvinfo -v -v "${f%.*}.mkv" | sed -e '\''/+ Cluster/q'\'' > "${f%.mkv}-mkvi.txt" ; IFS=#; readlink -f ${f##*/} >> _f.txt; done' -- {} +

rg.exe -l "KaxSeekHead" -g '*.txt'

# Problem files will be listed and highlighted in blue on the screen.
# Copy results from the screen to notepad++ or other text editor.
# Replace [-mkvi.txt\r\n] with [.mkv"\r\nmkclean "]
# Fix first and last lines of edited list.
# Copy&Paste in the bash window.
# Watch for 0 byte outputs in files if breaks or processor overload occur during processing.
Hope this helps. good luck.
